### ISSUE TITLE
Issue with the filterMessages method when doing msg.upscale

### ISSUE THREAD

**Issue by d400800** [UrielCh/midjourney-client#18]
Hello,
I encountered an issue with the upscale method results in the following error: "waitMessage still waiting for a 100% processed status after 0 refresh".
![upscale-issue-debug](https://github.com/UrielCh/midjourney-client/assets/20426760/60819bd7-958c-4b91-9bc7-705ba86745e8)

I debugged the code and found out, that the issue is related to this line:
`matches = matches.filter((item) => item.prompt!.name.includes(`#${imgId}`));`

In this case, item.prompt.name is '' (empty string), and imgId is part of the "source" property.

**Comment by d400800** [comment]
Error stack:
Error: waitMessage still waiting for a 100% processed status after 0 refresh
    at Midjourney.waitMessageInternal (C:\exposebox-git\miscellanea\node_modules\midjourney-discord-api\script\src\Midjourney.js:807:15)
    at async Midjourney.waitComponents (C:\exposebox-git\miscellanea\node_modules\midjourney-discord-api\script\src\Midjourney.js:567:21)
    at async Midjourney.callCustomComponents (C:\exposebox-git\miscellanea\node_modules\midjourney-discord-api\script\src\Midjourney.js:502:16)
    at async run (C:\exposebox-git\miscellanea\midjourney\discord-midjourney-api.js:42:22)

**Comment by UrielCh** [comment]
Fixed.

Will be release within the day

**Comment by UrielCh** [comment]
fixed in 1.0.5
